#!/bin/bash

DEST=/custom/scripts
REVS_DIR=/custom/.scripts_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/.scripts~

mkdir -p ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV} && \
ln -s -f ${NEW_REV} ${DEST} && \
find ${REVS_DIR} -maxdepth 1 -mindepth 1 ! -name ${DEPLOYMENT_ID} -exec rm -rf {} \;

DEST=/custom/puppet
REVS_DIR=/custom/.puppet_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/.puppet~

mkdir -p ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV} && \
ln -s -f ${NEW_REV} ${DEST} && \
find ${REVS_DIR} -maxdepth 1 -mindepth 1 ! -name ${DEPLOYMENT_ID} -exec rm -rf {} \;
