#!/bin/bash

DEST=/custom/scripts
REVS_DIR=/custom/.scripts_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/.scripts~

mkdir -p ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV}

if [ -L ${DEST} ]; then
	OLD_REV=`readlink -nf ${DEST}`
fi
ln -s ${NEW_REV} ${DEST}
if [ -o ${OLD_REV} ]; then
	rm -rf ${OLD_REV}
	unset OLD_REV
fi

DEST=/custom/puppet
REVS_DIR=/custom/.puppet_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/.puppet~

mkdir -p ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV}

if [ -L ${DEST} ]; then
	OLD_REV=`readlink -nf ${DEST}`
fi
ln -s ${NEW_REV} ${DEST}
if [ -o ${OLD_REV} ]; then
	rm -rf ${OLD_REV}
	unset OLD_REV
fi
