#!/bin/bash

DEST=/custom/scripts
REVS_DIR=/custom/.scripts_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/.scripts~

mkdir ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV}
OLD_REV=`readlink -nf ${DEST}`
ln -s ${NEW_REV} ${DEST}
rm -rf ${OLD_REV}


DEST=/custom/puppet
REVS_DIR=/custom/.puppet_revs
NEW_REV=${REVS_DIR}/${DEPLOYMENT_ID}
TMP_REV=/custom/puppet

mkdir ${REVS_DIR}
mv ${TMP_REV} ${NEW_REV}
OLD_REV=`readlink -nf ${DEST}`
ln -s ${NEW_REV} ${DEST}
rm -rf ${OLD_REV}
